#!/usr/bin/env tsx
/**
 * 自动化拆分 hexagrams.ts 为64个独立文件
 * 
 * 功能：
 * 1. 读取 src/content/hexagrams.ts 的 hexagramContents 数组
 * 2. 为每个卦生成独立文件 src/content/hexagrams/all/{slug}.ts
 * 3. 生成 src/content/hexagrams/meta.ts 的 HEXAGRAM_META 数组
 * 4. 生成 src/content/hexagrams/loader.ts 的 HEXAGRAM_MODULES 映射表
 */

import * as fs from 'fs';
import * as path from 'path';

// 导入原始数据（从备份文件）
import { hexagramContents } from './hexagrams-backup';
import type { HexagramContent } from '../src/content/hexagrams/types';

const PROJECT_ROOT = path.join(__dirname, '..');
const OUTPUT_DIR = path.join(PROJECT_ROOT, 'src/content/hexagrams/all');
const META_FILE = path.join(PROJECT_ROOT, 'src/content/hexagrams/meta.ts');
const LOADER_FILE = path.join(PROJECT_ROOT, 'src/content/hexagrams/loader.ts');

/**
 * 生成 slug（格式：01-qian）
 */
function generateSlug(hex: HexagramContent): string {
  const id = String(hex.id).padStart(2, '0');
  // 清理拼音，只保留小写字母
  const pinyin = hex.namePinyin
    .toLowerCase()
    .replace(/[^a-z]/g, '');
  return `${id}-${pinyin}`;
}

/**
 * 生成单个卦象文件内容
 */
function generateHexagramFile(hex: HexagramContent, slug: string): string {
  // 使用 JSON.stringify 来序列化数据，然后添加类型导入
  const jsonContent = JSON.stringify(hex, null, 2);
  
  return `// ${hex.nameZh} (${hex.name.en}) - Hexagram ${hex.id}
// Auto-generated from scripts/split-hexagrams.ts

import type { HexagramContent } from '../types';

const hexagram: HexagramContent = ${jsonContent};

export default hexagram;
`;
}

/**
 * 生成 meta.ts 文件内容
 */
function generateMetaFile(hexagrams: HexagramContent[]): string {
  const metaItems = hexagrams.map(hex => {
    const slug = generateSlug(hex);
    return `  {
    id: ${hex.id},
    slug: '${slug}',
    name: ${JSON.stringify(hex.name)},
    nameZh: '${hex.nameZh}',
    namePinyin: '${hex.namePinyin}',
    trigramUpper: ${JSON.stringify(hex.trigramUpper)},
    trigramLower: ${JSON.stringify(hex.trigramLower)},
    symbolUpper: '${hex.symbolUpper}',
    symbolLower: '${hex.symbolLower}',
  }`;
  });

  return `// Hexagram meta information (lightweight index)
// Auto-generated by scripts/split-hexagrams.ts

import type { Localized } from './types';

export type HexagramMeta = {
  id: number;
  slug: string;
  name: Localized;
  nameZh: string;
  namePinyin: string;
  trigramUpper: Localized;
  trigramLower: Localized;
  symbolUpper: string;
  symbolLower: string;
};

export const HEXAGRAM_META: HexagramMeta[] = [
${metaItems.join(',\n')}
];

export function getHexagramMeta(id: number): HexagramMeta | undefined {
  return HEXAGRAM_META.find((h) => h.id === id);
}

export function getHexagramMetaBySlug(slug: string): HexagramMeta | undefined {
  return HEXAGRAM_META.find((h) => h.slug === slug);
}
`;
}

/**
 * 生成 loader.ts 文件内容
 */
function generateLoaderFile(hexagrams: HexagramContent[]): string {
  const imports = hexagrams.map(hex => {
    const slug = generateSlug(hex);
    return `  ${hex.id}: () => import('./all/${slug}')`;
  });

  return `// Hexagram content loader with on-demand imports
// Auto-generated by scripts/split-hexagrams.ts

import type { HexagramContent, HexagramView, Lang } from './types';
import { getHexagramMeta } from './meta';

/**
 * Explicit module mapping for better bundler compatibility
 */
const HEXAGRAM_MODULES: Record<
  number,
  () => Promise<{ default: HexagramContent }>
> = {
${imports.join(',\n')}
};

/**
 * Load complete hexagram content (new API)
 */
export async function getHexagramContent(
  id: number
): Promise<HexagramContent | null> {
  const loader = HEXAGRAM_MODULES[id];
  if (!loader) {
    console.error(\`Hexagram \${id} not found in HEXAGRAM_MODULES\`);
    return null;
  }
  
  try {
    const mod = await loader();
    return mod.default;
  } catch (error) {
    console.error(\`Failed to load hexagram \${id}:\`, error);
    return null;
  }
}

/**
 * Get hexagram view (compatibility layer)
 * Maintains the same function signature and return structure as before
 */
export async function getHexagramView(
  id: number,
  lang: Lang
): Promise<HexagramView | null> {
  const content = await getHexagramContent(id);
  if (!content) return null;

  // Convert HexagramContent to flattened HexagramView structure
  return {
    id: content.id,
    name: content.name[lang],
    nameZh: content.nameZh,
    namePinyin: content.namePinyin,
    descriptionShort: content.descriptionShort[lang],
    trigramUpper: content.trigramUpper[lang],
    trigramLower: content.trigramLower[lang],
    symbolUpper: content.symbolUpper,
    symbolLower: content.symbolLower,
    judgement: content.judgement[lang],
    imageText: content.imageText[lang],
    lines: content.lines.map((line) => ({
      index: line.index,
      text: line.text[lang],
      original: line.original,
    })),
    summary: {
      general: content.initialSummary.general[lang],
      tone: content.initialSummary.tone,
      scenes: content.initialSummary.scenes
        ? {
            love: content.initialSummary.scenes.love?.[lang],
            career: content.initialSummary.scenes.career?.[lang],
            wealth: content.initialSummary.scenes.wealth?.[lang],
            health: content.initialSummary.scenes.health?.[lang],
          }
        : undefined,
    },
  };
}

/**
 * Preload hexagram content (optional optimization)
 */
export function preloadHexagram(id: number): void {
  const loader = HEXAGRAM_MODULES[id];
  if (loader) {
    loader().catch(err => console.error(\`Failed to preload hexagram \${id}:\`, err));
  }
}
`;
}

/**
 * 主执行函数
 */
async function main() {
  console.log('🚀 Starting hexagram split process...\n');

  // 1. 验证输入数据
  console.log(`📊 Found ${hexagramContents.length} hexagrams in source file`);
  
  if (hexagramContents.length !== 64) {
    console.error(`❌ Error: Expected 64 hexagrams, but found ${hexagramContents.length}`);
    process.exit(1);
  }

  // 2. 确保输出目录存在
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    console.log(`📁 Created output directory: ${OUTPUT_DIR}`);
  }

  // 3. 生成每个卦象的独立文件
  console.log('\n📝 Generating individual hexagram files...');
  const slugs: string[] = [];
  
  for (const hex of hexagramContents) {
    const slug = generateSlug(hex);
    slugs.push(slug);
    
    const fileName = `${slug}.ts`;
    const filePath = path.join(OUTPUT_DIR, fileName);
    const content = generateHexagramFile(hex, slug);
    
    fs.writeFileSync(filePath, content, 'utf-8');
    console.log(`  ✅ ${fileName} (${hex.nameZh})`);
  }

  // 4. 生成 meta.ts
  console.log('\n📝 Generating meta.ts...');
  const metaContent = generateMetaFile(hexagramContents);
  fs.writeFileSync(META_FILE, metaContent, 'utf-8');
  console.log(`  ✅ meta.ts (${hexagramContents.length} entries)`);

  // 5. 生成 loader.ts
  console.log('\n📝 Generating loader.ts...');
  const loaderContent = generateLoaderFile(hexagramContents);
  fs.writeFileSync(LOADER_FILE, loaderContent, 'utf-8');
  console.log(`  ✅ loader.ts (${hexagramContents.length} dynamic imports)`);

  // 6. 生成 index.ts（统一导出）
  console.log('\n📝 Generating index.ts...');
  const indexContent = `// Unified exports for hexagram content
// Auto-generated by scripts/split-hexagrams.ts

export * from './types';
export * from './meta';
export * from './loader';
`;
  const indexFile = path.join(PROJECT_ROOT, 'src/content/hexagrams/index.ts');
  fs.writeFileSync(indexFile, indexContent, 'utf-8');
  console.log(`  ✅ index.ts`);

  // 7. 总结
  console.log('\n' + '='.repeat(60));
  console.log('✨ Split completed successfully!');
  console.log('='.repeat(60));
  console.log(`📦 Generated files:`);
  console.log(`   - 64 hexagram files in: ${OUTPUT_DIR}`);
  console.log(`   - meta.ts: ${META_FILE}`);
  console.log(`   - loader.ts: ${LOADER_FILE}`);
  console.log(`   - index.ts: ${indexFile}`);
  console.log('\n📋 Next steps:');
  console.log('   1. Run: npm run build');
  console.log('   2. Test the application');
  console.log('   3. Update import paths in components');
  console.log('   4. Backup old hexagrams.ts → hexagrams-old.ts');
  console.log('');
}

// 执行
main().catch(error => {
  console.error('❌ Error during split process:', error);
  process.exit(1);
});

