// Hexagram content loader with on-demand imports
// Auto-generated by scripts/split-hexagrams.ts

import type { HexagramContent, HexagramView, Lang } from './types';
import { getHexagramMeta } from './meta';

/**
 * Explicit module mapping for better bundler compatibility
 */
const HEXAGRAM_MODULES: Record<
  number,
  () => Promise<{ default: HexagramContent }>
> = {
  1: () => import('./all/01-qian'),
  2: () => import('./all/02-kun'),
  3: () => import('./all/03-zhun'),
  4: () => import('./all/04-meng'),
  5: () => import('./all/05-xu'),
  6: () => import('./all/06-song'),
  7: () => import('./all/07-shi'),
  8: () => import('./all/08-bi'),
  9: () => import('./all/09-xiaochu'),
  10: () => import('./all/10-lv'),
  11: () => import('./all/11-tai'),
  12: () => import('./all/12-pi'),
  13: () => import('./all/13-tongren'),
  14: () => import('./all/14-dayou'),
  15: () => import('./all/15-qian'),
  16: () => import('./all/16-yu'),
  17: () => import('./all/17-sui'),
  18: () => import('./all/18-gu'),
  19: () => import('./all/19-lin'),
  20: () => import('./all/20-guan'),
  21: () => import('./all/21-shihe'),
  22: () => import('./all/22-bi'),
  23: () => import('./all/23-bo'),
  24: () => import('./all/24-fu'),
  25: () => import('./all/25-wuwang'),
  26: () => import('./all/26-dachu'),
  27: () => import('./all/27-yi'),
  28: () => import('./all/28-daguo'),
  29: () => import('./all/29-kan'),
  30: () => import('./all/30-li'),
  31: () => import('./all/31-xian'),
  32: () => import('./all/32-heng'),
  33: () => import('./all/33-dun'),
  34: () => import('./all/34-dazhuang'),
  35: () => import('./all/35-jin'),
  36: () => import('./all/36-mingyi'),
  37: () => import('./all/37-jiaren'),
  38: () => import('./all/38-kui'),
  39: () => import('./all/39-jian'),
  40: () => import('./all/40-xie'),
  41: () => import('./all/41-sun'),
  42: () => import('./all/42-yi'),
  43: () => import('./all/43-guai'),
  44: () => import('./all/44-gou'),
  45: () => import('./all/45-cui'),
  46: () => import('./all/46-sheng'),
  47: () => import('./all/47-kun'),
  48: () => import('./all/48-jing'),
  49: () => import('./all/49-ge'),
  50: () => import('./all/50-ding'),
  51: () => import('./all/51-zhen'),
  52: () => import('./all/52-gen'),
  53: () => import('./all/53-jian'),
  54: () => import('./all/54-guimei'),
  55: () => import('./all/55-feng'),
  56: () => import('./all/56-lv'),
  57: () => import('./all/57-xun'),
  58: () => import('./all/58-dui'),
  59: () => import('./all/59-huan'),
  60: () => import('./all/60-jie'),
  61: () => import('./all/61-zhongfu'),
  62: () => import('./all/62-xiaoguo'),
  63: () => import('./all/63-jiji'),
  64: () => import('./all/64-weiji')
};

/**
 * Load complete hexagram content (new API)
 */
export async function getHexagramContent(
  id: number
): Promise<HexagramContent | null> {
  const loader = HEXAGRAM_MODULES[id];
  if (!loader) {
    console.error(`Hexagram ${id} not found in HEXAGRAM_MODULES`);
    return null;
  }
  
  try {
    const mod = await loader();
    return mod.default;
  } catch (error) {
    console.error(`Failed to load hexagram ${id}:`, error);
    return null;
  }
}

/**
 * Get hexagram view (compatibility layer)
 * Maintains the same function signature and return structure as before
 */
export async function getHexagramView(
  id: number,
  lang: Lang
): Promise<HexagramView | null> {
  const content = await getHexagramContent(id);
  if (!content) return null;

  // Convert HexagramContent to flattened HexagramView structure
  return {
    id: content.id,
    name: content.name[lang],
    nameZh: content.nameZh,
    namePinyin: content.namePinyin,
    descriptionShort: content.descriptionShort[lang],
    trigramUpper: content.trigramUpper[lang],
    trigramLower: content.trigramLower[lang],
    symbolUpper: content.symbolUpper,
    symbolLower: content.symbolLower,
    judgement: content.judgement[lang],
    imageText: content.imageText[lang],
    lines: content.lines.map((line) => ({
      index: line.index,
      text: line.text[lang],
      original: line.original,
    })),
    summary: {
      general: content.initialSummary.general[lang],
      tone: content.initialSummary.tone,
      scenes: content.initialSummary.scenes
        ? {
            love: content.initialSummary.scenes.love?.[lang],
            career: content.initialSummary.scenes.career?.[lang],
            wealth: content.initialSummary.scenes.wealth?.[lang],
            health: content.initialSummary.scenes.health?.[lang],
          }
        : undefined,
    },
  };
}

/**
 * Preload hexagram content (optional optimization)
 */
export function preloadHexagram(id: number): void {
  const loader = HEXAGRAM_MODULES[id];
  if (loader) {
    loader().catch(err => console.error(`Failed to preload hexagram ${id}:`, err));
  }
}
